layout: post
title: Tipan's Webpage
logo: images/tipan_child.jpg
description: I had to wait for github to do this!
show_downloads: true
markdown: kramdown
mathjax: true
google_analytics:
theme: jekyll-theme-minimal
twitter: tipanverella
email: tipan.verella@gmail.com
